import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a1a',
  },
  content: {
    flex: 1,
    padding: 20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    paddingTop: 10,
  },
  backText: {
    color: '#4ecdc4',
    fontSize: 18,
    fontWeight: 'bold',
  },
  title: {
    fontSize: 32,
    color: '#fff',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 50,
    paddingTop: 20,
  },
  sectionTitle: {
    fontSize: 20,
    color: '#fff',
    fontWeight: '600',
    marginLeft: 20,
    marginTop: 30,
    marginBottom: 10,
  },
  button: {
    backgroundColor: '#4ecdc4',
    paddingHorizontal: 30,
    paddingVertical: 20,
    borderRadius: 15,
    marginBottom: 20,
    width: '80%',
    alignItems: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  input: {
    backgroundColor: '#2d2d2d',
    color: '#fff',
    padding: 15,
    borderRadius: 10,
    fontSize: 18,
    borderWidth: 1,
    borderColor: '#4ecdc4',
  },
  label: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  card: {
    backgroundColor: '#2d2d2d',
    padding: 15,
    borderRadius: 10,
    marginBottom: 15,
  },
  timerContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  phase: {
    fontSize: 24,
    color: '#ff6b6b',
    marginBottom: 20,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  time: {
    fontSize: 96,
    color: '#fff',
    fontWeight: 'bold',
    fontVariant: ['tabular-nums'],
  },
  roundText: {
    fontSize: 20,
    color: '#aaa',
  },
  controlsTop: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  controlsBottom: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    paddingHorizontal: 40,
  },
  skipButtonSmall: {
    backgroundColor: '#ff9500',
    paddingHorizontal: 25,
    paddingVertical: 10,
    borderRadius: 20,
    flex: 1,
    marginHorizontal: 10,
  },
  skipTextSmall: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  buttonSecondary: {
    backgroundColor: '#ff6b6b',
    paddingHorizontal: 30,
    paddingVertical: 12,
    borderRadius: 25,
    minWidth: 100,
  },
  workoutName: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    flex: 1,
    textAlign: 'center',
    marginLeft: 10,
  },
  bar: {
    height: 25,
    borderRadius: 5,
    marginHorizontal: 10,
  },
  congratsTitle: {
    fontSize: 32,
    color: '#4ecdc4',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
  },
  congratsStats: {
    fontSize: 22,
    color: '#fff',
    textAlign: 'center',
    marginBottom: 10,
    fontWeight: '600',
  },
});
